title: Pledger.io

release:
  version: 3.8.0
  date: 2025-01-03

github:
  repository: pledger-io/user-documentation

source: docs
disable_disk_cache: true

plugins:
  - jekyll-asciidoc
  - jekyll-last-modified-at
  - jekyll-toc

defaults:
  - scope:
      path: ""
    values:
      toc: true

keep_files:
  - images/generated

asciidoctor:
  base_dir: :docdir
  safe: unsafe

last-modified-at:
  date-format: '%d-%b-%y'

aux_links:
  "Bug Tracker":
    "https://github.com/pledger-io/user-interface/issues"
  "Source code":
    "https://github.com/pledger-io"
